### ISSUE TITLE
XGL cache creator tool

### ISSUE THREAD

**Issue by s-perron** [GPUOpen-Drivers/xgl#64]
# Background

There has been a lot of work in LLPC over the past 9 months to implement [relocatable shaders](https://github.com/s-perron/llpc/blob/reloc_doc/docs/DdnRelocatableShaderElf.md).  These were intended to provide a way to compile shaders “offline”, that is without running a vulkan application.  However for that to be useful, there must be a way for a vulkan application to make use of the precompiled shaders.

To this end, we want to write a tool that will take the precompiled shaders and build a file whose contents can be passed as the [initial data](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkPipelineCacheCreateInfo.html) to <code>[vkCreatePipelineCache](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCreatePipelineCache.html)</code>.  This tool should live in the XGL repository because XGL controls the format of the cache when it is serialized by <code>[vkGetPipelineCacheData](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkGetPipelineCacheData.html)</code>.

This will be a standalone tool that will have its own subdirectory in the [tools directory](https://github.com/GPUOpen-Drivers/xgl/tree/dev/icd/tools).

# Implementation details

## Prerequisites

*   Game developers must be able to use `amdllpc` to compile shaders and get an elf file.
*   The elf file will contain the cache hash for the shader/pipeline in the PAL metadata.
    *   The PAL metadata already contains the [internal pipeline hash](https://github.com/GPUOpen-Drivers/llpc/blob/2d7ea18fcee0d01401aa9fc4345eed9135b78223/lgc/state/PalMetadata.cpp#L454), but that seems to be [compacted to 64-bits](https://github.com/GPUOpen-Drivers/llpc/blob/5c60189d73b50378cbed9af081ce0717881c414f/llpc/context/llpcPipelineContext.h#L124) before it is [assigned](https://github.com/GPUOpen-Drivers/llpc/blob/5c60189d73b50378cbed9af081ce0717881c414f/llpc/context/llpcPipelineContext.cpp#L242).  Could this be expanded to 128-bits?
    *   This entry is only added during pipeline [finalization](https://github.com/GPUOpen-Drivers/llpc/blob/2d7ea18fcee0d01401aa9fc4345eed9135b78223/lgc/state/PalMetadata.cpp#L454), so the PAL metadata for a relocatable shader does not currently contain it.
    *   If we decide we only want this to work for relocatable shaders, then we could add something specific to relocatable shaders, but I would like something more general.

### Command line interface

```
xlg_cache_creator [options] <input elf files>

Options:

-o <filename>          - The filename to output the cache data to. 
                         Required.
-device_id=<device id> - The device id of the device this cache will be used on.
                         The device id can be found at
                         https://devicehunt.com/view/type/pci/vendor/1002.
                         If this option is not provided, the device id will be
                         queried from the runtime.
-uuid=<uuid>           - The uuid for the specific driver and machine.
                         <How can the uuid be found?>
                         If this option is not provided, the device id will be
                         queried from the runtime.
```

### Algorithm

*   Open the output file and set the position past the header size
*   [Initialize the key platform](https://github.com/GPUOpen-Drivers/xgl/blob/feb87bf013f2b4bd16f7a1da39a5a97fdaa7470d/icd/api/vk_physical_device.cpp#L527) using the uuid.
*   For each input elf file
    *   Open the file, and copy the contents to the output buffer.
    *   Add the contents of the file to the hash context
        *   I would like to avoid having everything in memory at the same time.
*   [Output the PipelineBinaryCachePrivateHeader](https://github.com/GPUOpen-Drivers/xgl/blob/dev/icd/api/pipeline_binary_cache.cpp) using the standard malloc and free as the allocators.
*   Output the header generated by <code>[vkGetPipelineCacheData](https://github.com/GPUOpen-Drivers/xgl/blob/dev/icd/api/vk_pipeline_cache.cpp)</code>

# Task list

- [X] Modify the internal pipeline hash to be a 128-bit value for the cache hash. (Cannot do)
- [ ] Modify LLPC to emit a new elf section `llpc_cache_hash` contianing the 128-bit hash for the ELF file being generated.
- [x] Modify the unlinked shader path in LLPC to add the internal pipeline hash to the metadata.
- [ ] Refactor [`PhysicalDevice::InitializePlatformKey`](https://github.com/GPUOpen-Drivers/xgl/blob/feb87bf013f2b4bd16f7a1da39a5a97fdaa7470d/icd/api/vk_physical_device.cpp#L527) so:
    *   The UUID is passed in as a parameter and used in place of the device properties.
    *   Allocation functions are passed as parameters so the vk instance is not needed.
    *   The time stamp is not used since the UUID is already the result of hashing the time stamp.
    *   The platform key that is created is returned.
    *   Make it available to the cache creator tool without needing a `PhysicalDevice`.
- [x] Refactor [`CalculateHashId`](https://github.com/GPUOpen-Drivers/xgl/blob/dev/icd/api/pipeline_binary_cache.cpp):
    *   Replace the `pInstance` parameter with the allocation and deallocation functions, so that an `Instance` is not needed.
    *   Make it available to the cache creator tool.
- [x] Refactor [`vkGetPipelineCacheData`](https://github.com/GPUOpen-Drivers/xgl/blob/dev/icd/api/vk_pipeline_cache.cpp) code that writes the header into a function (`WriteVkCacheHeader`?) the cache creator tool can call.
- [x]  Write the cache creator tool:
    *   Uses the new `InitializePlatformKey`, `CalculateHashId`, and `WriteVkCacheHeader`.
    *   Uses the [`ElfReader`](https://github.com/GPUOpen-Drivers/pal/blob/dev/inc/util/palElfReader.h) to read the elf and extract the PAL metadata.
    *   Uses [`MsgPackReader`](https://github.com/GPUOpen-Drivers/pal/blob/dev/inc/util/palMsgPack.h) to read the PAL metadata to get the hash.

**Comment by s-perron** [comment]
> Modify the internal pipeline hash to be a 128-bit value for the cache hash.

This might not be so easy. PAL makes use of the internal pipeline cache hash, and they expect it to be 64-bits.  Changing that would be a big change.

**Comment by JonCampbell407** [comment]
Can you modify amdllpc to output the 128 bit hash in addition to the elf?  Then the input to xgl_cache_creator would be a set of 128 bit hash and elf pairs.

Not really tied to this proposal but it is a bit concerning that we have two different mechanisms for calculating a hash that is stored in the same cache.  I'm not sure if this is going to cause issues.

I think the refactoring you mention should be fine.  Are you planning to keep the code in the same files they are now or put them in a separate file to minimize what needs to be compiled into xgl_cache_creator?

**Comment by s-perron** [comment]
> Can you modify amdllpc to output the 128 bit hash in addition to the elf? Then the input to xgl_cache_creator would be a set of 128 bit hash and elf pairs.

If you are thinking of amdllpc output two separate files then I would not like that idea.  I want to the hash to somehow be included in the elf file so that less book keeping needs to be down both other tools.  However, I am will to do that if that is what you want.

My preference would be to do something like add a new section to the elf that contains the hash, or a new pal metadata entry.  The elf section would partially do what you want, "minimize what needs to be compiled into xlg_cache_creator", because the tool won't need to read the pal metadata.

> Are you planning to keep the code in the same files they are now or put them in a separate file to minimize what needs to be compiled into xgl_cache_creator?

I would like a separate file, but I'm not too concerned about that.

**Comment by JonCampbell407** [comment]
You can have a section of the elf that PAL ignores.  GetGenericSection() and SetGenericSection() are the functions to do that in PAL.
